CREATE TABLE IF NOT EXISTS `sample_runs` (
    `id`                CHAR(36)        NOT NULL,
    `user_id`           CHAR(36)        NOT NULL,
    `problem_id`        CHAR(36)        NOT NULL,
    `language_key`      VARCHAR(20)     NOT NULL,
    `sample_case_id`    CHAR(36)        NULL,
    `source_code`       MEDIUMTEXT      NOT NULL,
    `input_data`        TEXT            NOT NULL,
    `status`            VARCHAR(20)     NOT NULL DEFAULT 'QUEUED',
    `output_data`       MEDIUMTEXT      NULL,
    `error_message`     TEXT            NULL,
    `stream_message_id` VARCHAR(64)     NULL,
    `enqueued_at`       DATETIME(6)     NULL,
    `created_at`        DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `updated_at`        DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `started_at`        DATETIME(6)     NULL,
    `finished_at`       DATETIME(6)     NULL,
    `expires_at`        DATETIME(6)     NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_sample_runs_user` (`user_id`),
    INDEX `idx_sample_runs_status` (`status`),
    INDEX `idx_sample_runs_expires` (`expires_at`),
    CONSTRAINT `fk_sample_runs_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sample_runs_problem` FOREIGN KEY (`problem_id`) REFERENCES `problems` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sample_runs_language` FOREIGN KEY (`language_key`) REFERENCES `language_configs` (`key`) ON DELETE RESTRICT,
    CONSTRAINT `fk_sample_runs_case` FOREIGN KEY (`sample_case_id`) REFERENCES `test_cases` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
